### ISSUE TITLE
VTS/WF Std 3 (WEID):  Implement Spec Change 12

### ISSUE THREAD

**Issue by danielmarschall** [ViaThinkSoft/standards#1]
@wehowski 
Kannst du eine OID für WEID Spec Change #12 (09.09.2024) sowie einen Eintrag auf weid.info für den Spec Change #12 machen, wie folgt:

**_In accordiance with RFC3406, the URN namespace of WEID is "urn:x-weid:" (whereas "x-" stands for an unregistered experimental URN).  Hence, "weid:2-RR-2" can be written as "urn:x-weid:2-RR-2"._**

---

~~@danielmarschall~~
~~In VTS/WF Std. 3 einfügen~~
=> Fixed 11.9.2024

**Comment by danielmarschall** [comment]
@wehowski 
Ich habe https://github.com/frdl/weid/blob/gh-pages/implementations.md geändert
aber diese Seite hat sich nicht geändert: https://co.weid.info/implementations.html
Ich dachte GitHub wird zu weid.info synchronisiert, weil es eine github page ist?

**Comment by wehowski** [comment]
Hallo @danielmarschall 
bitte Entschuldige die Verspätung!
Ich war die letzten 2 Tage krank und muss nun nacharbeiten.

Ja ist github, aber:
Die Seite liegt doch jetzt hier: https://github.com/WEID-Consortium/weid.info/blob/gh-pages/implementations.md
Habe die Seite geändert.

**Comment by danielmarschall** [comment]
Hallo Melanie,

es freut mich, dass es dir wieder besser geht!

Bzgl. GitHub: Wir scheinen hier auf GitHub ein Duplikat zu haben. Kann 
man da nicht eines von löschen?

Es gibt hier ein Dilemma:

https://github.com/frdl/weid/blob/gh-pages/

-> hier liegt die aktuelle Version vom PHP und JS Converter (habe ich 
gestern geändert)

-> hier lädt sich OIDplus den Converter im Vendor Update herunter (aber 
das kann ich natürlich ändern!)

-> auf diesen Converter verlinkt die offizielle 
weid.info/implementations.html Seite

https://github.com/WEID-Consortium/weid.info/tree/gh-pages

-> Diese Seite ist scheinbar die Live-Version von weid.info

Wir sollten diesbezüglich eine Lösung finden, denn es wird etwas 
unübersichtlich, wenn wir Duplikate haben, die unterschiedliche 
Funktionen haben :-)

Viele Grüße

Daniel

**Comment by danielmarschall** [comment]
Ich wollte grad den Converter PHP/JS ändern, aber ich habe keine Schreibrechte.

Bitte gib mir Schreibrechte und übertrage meine PHP/JS änderungen am Converter. Vielen Dank!

**Comment by wehowski** [comment]
Hallo Daniel,
sorry dachte Du hättest schon Schreibrechte.
Hab Dir nun Adminrechte gegeben und die beiden Dateien geändert.

co,weid.info hatte ich doch eingeführt weil es sonst immer so ein hin und her mit der Hauptdomain und dem DNS gab, und um die Domain noch nutzen zu können.  https://github.com/WEID-Consortium hatte ich eingerichtet um die Dinge besser von frdl abzugliedern und für die Übersicht.  

> Wir sollten diesbezüglich eine Lösung finden, denn es wird etwas
> unübersichtlich, wenn wir Duplikate haben, die unterschiedliche
> Funktionen haben :-)

Was schlägst Du vor? Sollen wir das alte Repository löschen?

Viele Grüße
Melanie

**Comment by danielmarschall** [comment]
Wenn das alte Repository keine Verwendung mehr hat (bis auf die Links), ja, dann sollte es gelöscht werden.

Die Links von OIDplus und WEID-Consortium werde ich dann anpassen auf das neue Repo.

**Comment by wehowski** [comment]
Ok, soll ich es sofort löschen, bzw. oder Du kannst mir Bescheid geben, und wir etwas warten, bis die Links sich überall geändert haben?

**Comment by danielmarschall** [comment]
So, ich habe die Links hier angepasst: https://co.weid.info/implementations.html
und auch im OIDplus Core habe ich die Links angepasst.

Das Repro könnte eigentlich gelöscht werden, aber ich frage mich, geht dann das WEID-Consortium auch weg, weil es ein Fork ist?

**Comment by wehowski** [comment]
Mh. Glaube eigentlich nicht, aber wissen tue ich es nicht zu 100%!?
Alternativ können wir das repository "archivieren und auf read-only" stellen?

**Comment by danielmarschall** [comment]
Andere idee: Alles rauslöschen und durch eine Readme ersetzen, die auf das richtige Repo verweist.

**Comment by wehowski** [comment]
Habe alle rausgelöscht, bis auf zunächst drei Dateien (die Konverter und das favicon) falls die noch irgendwo verlinkt sind:
https://github.com/frdl/weid/tree/gh-pages

**Comment by danielmarschall** [comment]
Danke. Ich würd die aber auch gerne rauslöschen. Wenn es irgendwo verlinkt ist, wird derjenige schon gucken und den Link korrigieren. Ich möchte verhindern, dass wir zwei Converter haben deren Versionen auseinanderlaufen

**Comment by wehowski** [comment]
Habe nun alle Dateien gelöscht, bis auf die Readme mit dem Link.

**Comment by danielmarschall** [comment]
Erstellt:  https://registry.frdl.de/?goto=oid%3A1.3.6.1.4.1.37553.8.1.8.1.6.1.12

Geändert:  https://github.com/WEID-Consortium/weid.info/blob/gh-pages/spec.md

Erweitert: https://github.com/ViaThinkSoft/standards/blob/main/viathinksoft-std-0003-weid.txt
